[package]
name = "fblog"
version = "3.0.1-alpha.0"
authors = ["Patrick Haun <bomgar85@googlemail.com>"]
license = "WTFPL"
categories = ["command-line-utilities"]
description = "json log viewer"
keywords = ["json", "log", "viewer" ]
repository = "https://github.com/brocode/fblog"
readme = "README.org"
edition = "2018"

[dependencies]
serde_json = "1.0"
clap = "2"
ansi_term = "0.12"
regex = "1"
hlua = "0.4"
lazy_static = "1.4.0"
handlebars = "4"
