on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  build:
    name: Release (github.com)
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: fblog
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v6
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: cargo build --release
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: musl-strip target/x86_64-unknown-linux-musl/release/fblog
      - run: cp ./target/x86_64-unknown-linux-musl/release/fblog fblog
      - run: sha512sum fblog > fblog.sha512sum
      - id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fblog
            fblog.sha512sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

